"
BlImageCache is an abstract super-class of the various image caches.

Public API and Key Messages

- message one   
- message two 
- (for bonus points) how to create instances.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.


    Implementation Points
"
Class {
	#name : #BlImageCache,
	#superclass : #Object,
	#category : #'GToolkit-Images-Cache'
}
