"
GToolkit-IPC (Inter-Process Communications):

- loads the dependencies for communicating with other Pharo images using TelePharo & Seamless
- provides convience classes for managing worker image pools, startup and shutdown
- provides the framework for inspecting objects in remote images
"
Class {
	#name : #ManifestGToolkitIPC,
	#superclass : #PackageManifest,
	#category : #'GToolkit-IPC-Manifest'
}
